move_minder/move_minder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('pwa.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

move_minder/tracker/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import HomePageView, SignupView, CustomLoginView, UserUpdateView, DashboardView, UserListView, UserDetailView, MoveListView, MoveDetailView, MoveCreateView, MoveUpdateView, MoveDeleteView,ParcelDetailView, ParcelCreateView, ParcelUpdateView, ParcelDeleteView, ReceivingView, LabelPreview, ShipParcelsView, EndReceivingView, ReceiveParcelView

app_name = "tracker"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("sign-up/", SignupView.as_view(), name="sign-up"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("users/", UserListView.as_view(), name="users-list"),
    path("users/<int:pk>/edit/", UserUpdateView.as_view(), name="edit-profile"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
    path("moves/", MoveListView.as_view(), name="moves-list"),
    path("moves/<int:pk>/", MoveDetailView.as_view(), name="move-detail"),
    path("moves/new/", MoveCreateView.as_view(), name="move-create"),
    path("moves/<int:pk>/edit/", MoveUpdateView.as_view(), name="move-update"),
    path("moves/<int:pk>/delete/", MoveDeleteView.as_view(), name="move-delete"),
    path("moves/<int:move_id>/parcels/<int:pk>/", ParcelDetailView.as_view(), name="parcel-detail"),
    path("moves/<int:pk>/parcels/new/", ParcelCreateView.as_view(), name="parcel-create"),
    path("moves/<int:move_id>/parcels/<int:pk>/edit/", ParcelUpdateView.as_view(), name="parcel-update"),
    path("moves/<int:move_id>/parcels/<int:pk>/delete/", ParcelDeleteView.as_view(), name="parcel-delete"),
    path("parcels/receiving/", ReceivingView.as_view(), name="receiving"),
    path("parcels/<int:pk>/receiving/update-status/", ReceiveParcelView.as_view(), name="receive-parcel"),
    path("labels/", LabelPreview.as_view(), name="label-preview"),
    path("moves/<int:move_id>/parcels/bulk-ship/", ShipParcelsView.as_view(), name="bulk-ship"),
    path("moves/<int:move_id>/end-receiving/", EndReceivingView.as_view(), name="end-receiving")
]

move_minder/tracker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import ModelForm
import json
from .models import Parcel, UserProfile, Move
from phonenumber_field.formfields import PhoneNumberField

class ParcelStatusForm(ModelForm):
    class Meta:
        model = Parcel
        fields = ["status"]

class SignUpForm(UserCreationForm):
    phone = PhoneNumberField()
    first_name = forms.CharField(max_length=40, required=True)
    last_name = forms.CharField(max_length=40, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "first_name", "last_name", "email", "phone"]

    def clean(self):
        cleaned_data = super(ModelForm, self).clean()
        return cleaned_data

    def is_valid(self):
        valid = super().is_valid()
        print(f"Valid: {valid}")
        if not valid:
            errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
            for field, field_errors in self.errors.items():
                if field != '__all__':
                    continue
                for error in field_errors:
                    errors.append(error)
        return valid

class UpdateUserForm(ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput, required=False)
    phone = PhoneNumberField()

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "first_name", "last_name", "email", "phone"]

        def __init__(self, *args, **kwargs):
            self.user = kwargs.get("instance", None)
            super().__init__(*args, **kwargs)

            self.fields["username"].initial = self.user.username
            self.fields["first_name"].initial = self.user.first_name
            self.fields["last_name"].initial = self.user.last_name
            self.fields["email"].initial = self.user.email

        def clean_password2(self):
            password1 = self.cleaned_data.get("password1")
            password2 = self.cleaned_data.get("password2")
            if password1 and password2 and password1 != password2:
                raise ValidationError("Passwords don't match")
            return password2

class MoveForm(ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = Move
        fields = ["nickname", "primary_user", "secondary_users", "start_date", "end_date", "origin_address1", "origin_address2", "origin_city", "origin_state_province", "origin_postal_code", "origin_country", "destination_address1", "destination_address2", "destination_city", "destination_state_province", "destination_postal_code", "destination_country"]

        def __init__(self, *args, request=None, **kwargs):
            self.user = kwargs.get("instance", None)
            super().__init__(*args, **kwargs)
            self.request = request

            if request is not None and request.resolver_match.url_name == "move-update":
                instance = kwargs.get("instance")
                for field in self.fields.keys():
                    self.field[field].initial = instance[field]

class ParcelForm(ModelForm):
    class Meta:
        model = Parcel
        fields = ["move_id", "type", "room", "contents", "photo", "weight", "status"]
    
        def __init__(self, *args, request=None, **kwargs):
            self.user = kwargs.get("instance", None)
            super().__init__(*args, **kwargs)
            self.request = request

            if request is not None and request.resolver_match.url_name == "parcel-update":
                instance = kwargs.get("instance")
                for field in self.fields.keys():
                    self.field[field].initial = instance[field]

move_minder/tracker/views.py
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django import forms
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.sites.requests import RequestSite
from django.contrib.sites.models import Site
from django.core.exceptions import ImproperlyConfigured
from django.db.models import Q, Count
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.base import TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import ParcelStatusForm, SignUpForm, UpdateUserForm, MoveForm, ParcelForm
import json
from .models import Move, Parcel, UserProfile
from move_minder.sitemaps import StaticViewSitemap
import os
from phonenumber_field.formfields import PhoneNumberField
import re

# Create your views here.
class SitemapMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        request_site = RequestSite(self.request)

        try:
            current_site = Site.objects.get_current(request_site)
        except ImproperlyConfigured:
            current_site = None

        context['current_site'] = current_site
        sitemap = StaticViewSitemap(request_site=request_site, current_site=current_site)
        context['sitemap'] = sitemap.get_urls()

        for url in context['sitemap']:
            url['name'] = " ".join(url['item'].split(":")[-1].split("-")).title()
        return context
    
class AnonymousUserMixin(UserPassesTestMixin):
    def test_func(self):
        return not self.request.user.is_authenticated
    
    def handle_no_permission(self):
        return HttpResponseRedirect(reverse_lazy("tracker:dashboard"))

class HomePageView(SitemapMixin, TemplateView):
    template_name = "tracker/home.html"

    """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # add additional context as necessary
        return context
    """

class SignupView(SitemapMixin, AnonymousUserMixin, CreateView):
    model = UserProfile
    template_name = "tracker/signup.html"
    success_url = reverse_lazy('tracker:login')
    form_class = SignUpForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = context.get("form")
        if form:
            context["form_errors"] = form.errors
        return context
    
    def form_valid(self, form):
        user = form.save()
        phone = form.cleaned_data["phone"]
        UserProfile.objects.create(user=user, phone=phone)
        return super().form_valid(form)
    
    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class CustomLoginView(SitemapMixin, AnonymousUserMixin, LoginView):
    model = UserProfile
    template_name = "tracker/login.html"
    success_url = reverse_lazy("tracker:dashboard")
    form_class = AuthenticationForm

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

class UserUpdateView(SitemapMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = "tracker/user_update.html"
    form_class = UpdateUserForm

    def get_initial(self):
        initial = super().get_initial()
        user = self.get_object()
        profile = UserProfile.objects.get(user=user)
        initial["phone"] = profile.phone
        return initial

    def get_success_url(self):
        return reverse("tracker:user-detail", kwargs={"pk": self.request.user.id})
    
    def get(self, request, *args, **kwargs):
        url = request.path
        user = User.objects.select_related("userprofile").get(id=request.user.id)
        history = user.userprofile.recent_pages
        for i in range(len(history)):
            if history[i]["name"] == "Edit Profile":
                history.pop(i)
                break
        history.insert(0, { "name": "Edit Profile", "url": url })
        while len(history) > 10:
            history.pop()
        user.userprofile.recent_pages = history
        user.userprofile.save()
        return super().get(request, *args, **kwargs)
    
    def form_valid(self, form):
        user = form.save()
        phone = form.cleaned_data["phone"]
        UserProfile.objects.filter(user=user).update(phone=phone)
        return super().form_valid(form)

class DashboardView(SitemapMixin, LoginRequiredMixin, TemplateView):
    template_name = "tracker/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = date.today()
        try:
            user_id = self.request.user.id
            moves = Move.objects.filter(
                Q(primary_user=user_id) | Q(secondary_users__in=[user_id]),
            )

            upcoming = moves.filter(
                start_date__gte=today
            ).values(
                "id",
                "nickname",
                "start_date",
                "primary_user__first_name",
                "primary_user__last_name",
                "origin_city",
                "destination_city"
            ).order_by(
                "start_date", 
                "origin_city", 
                "destination_city"
            )
            context["moves"] = upcoming[:10]

            parcels_query = Parcel.objects.filter(move_id__in=moves).aggregate(
                packed=Count("id", filter=Q(status="Packed")),
                in_transit=Count("id", filter=Q(status="In Transit")),
                lost=Count("id", filter=Q(status="Lost")),
                received=Count("id", filter=Q(status="Received")),
                damaged=Count("id", filter=Q(status="Damaged")),
                accepted=Count("id", filter=Q(status="Accepted"))
            )

            parcels = {}
            if len(parcels_query) > 0:
                for key, value in parcels_query.items():
                    new_key = re.sub("_", " ", key.title())
                    parcels[new_key] = value
            else:
                parcels = {
                    "Packed": 0,
                    "In Transit": 0,
                    "Lost": 0,
                    "Received": 0,
                    "Damaged": 0,
                    "Accepted": 0
                }
            
            context["parcels"] = parcels

            recent = UserProfile.objects.filter(user=user_id).values("recent_pages")
            recent_pages = list(recent)[0]["recent_pages"][:10]
            context["recent_pages"] = recent_pages
            
        except Exception as e:
            print(e)
        return context

class UserListView(SitemapMixin, LoginRequiredMixin, ListView):
    model = User
    paginate_by = 50
    context_object_name = "users"

class UserDetailView(SitemapMixin, LoginRequiredMixin, DetailView):
    model = User
    template_name = "tracker/user_detail.html"

    def get_queryset(self):
        path = self.request.path_info.split("/")
        user_id = path[2]
        qs = User.objects.select_related("userprofile").filter(pk=user_id)
        return qs

class MoveListView(SitemapMixin, LoginRequiredMixin, ListView):
    paginate_by = 10
    context_object_name = "moves"

    def get_queryset(self):
        user = User.objects.get(pk=self.request.user.id)
        moves = Move.objects.select_related("primary_user").filter(Q(primary_user=user) | Q(secondary_users__in=[user])).order_by("-start_date")
        return moves
    
    def get(self, request, *args, **kwargs):
        url = request.path
        user = User.objects.select_related("userprofile").get(id=request.user.id)
        history = user.userprofile.recent_pages
        for i in range(len(history)):
            if history[i]["name"] == "My Moves":
                history.pop(i)
                break
        history.insert(0, { "name": "My Moves", "url": url })
        while len(history) > 10:
            history.pop()
        user.userprofile.recent_pages = history
        user.userprofile.save()
        return super().get(request, *args, **kwargs)

class MoveDetailView(SitemapMixin, LoginRequiredMixin, DetailView):
    model = Move

    def get_context_data(self, **kwargs):
        move_id = get_object_or_404(Move, pk=self.kwargs["pk"])

        context = super().get_context_data(**kwargs)
        parcels = Parcel.objects.filter(move_id=move_id)
        context["parcels"] = parcels
        parcel_status_query = parcels.aggregate(
            packed=Count("id", filter=Q(status="Packed")),
            in_transit=Count("id", filter=Q(status="In Transit")),
            lost=Count("id", filter=Q(status="Lost")),
            received=Count("id", filter=Q(status="Received")),
            damaged=Count("id", filter=Q(status="Damaged")),
            accepted=Count("id", filter=Q(status="Accepted"))
        )
        
        parcel_status = {}
        if len(parcel_status_query) > 0:
            for key, value in parcel_status_query.items():
                new_key = re.sub("_", " ", key.title())
                parcel_status[new_key] = value
        else:
            parcel_status = {
                "Packed": 0,
                "In Transit": 0,
                "Lost": 0,
                "Received": 0,
                "Damaged": 0,
                "Accepted": 0
            }
        
        context["parcel_status"] = parcel_status

        return context
    
    def get(self, request, *args, **kwargs):
        url = request.path
        user = User.objects.select_related("userprofile").get(id=request.user.id)

move_minder/tracker/templates/tracker/dashboard.html
{% extends "base.html" %}

{% block title %}
Dashboard | 
{% endblock %}

{% block main %}
<div class="px-4 lg:px-8 py-4 md:py-6 xl:py-8">
    <h2>Dashboard</h2>
    <section class="grid grid-cols-1 md:grid-cols-2 gap-6 sm:gap-7 md:gap-8 lg:gap-10 xl:gap-12 2xl:gap-16 mt-4 sm:mt-6 md:mt-8 lg:mt-12 xl:mt-16">
        <section class="card">
            <h3 class="text-center pb-3 border-b border-slate-400 dark:border-slate-600">Your Upcoming Moves</h3>
            <div class="h-full">
                {% if moves %}
                    <table id="upcoming-moves-table" class="pt-4 sm:pt-5 md:pt-7 lg:pt-9 xl:pt-10  border-collapse border border-slate-400 dark:border-slate-500 border-spacing-0 w-full table-auto text-center">
                        <thead class="bg-slate-200 dark:bg-slate-700">
                            <tr class="p-1 sm:p-2 lg:p3">
                                <th>Date</th>
                                <th>Nickname</th>
                                <th class="md:max-lg:hidden">Owner</th>
                                <th class="hidden md:table-cell">From</th>
                                <th class="hidden md:table-cell">To</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for move in moves %}
                                <tr class="border-t border-t-slate-400 dark:border-t-slate-500 px-1 sm:px-2 lg:px-3 sm:py-1 lg:py-2 hover:bg-slate-100 dark:hover:bg-slate-800">
                                    <td class="link">
                                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.start_date|date:"SHORT_DATE_FORMAT" }}</a>
                                    </td>
                                    <td class="link">
                                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.nickname }}</a>
                                    </td>
                                    <td class="link md:max-lg:hidden">
                                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.primary_user__first_name }} {{ move.primary_user__last_name }}</a>
                                    </td>
                                    <td class="hidden link md:table-cell">
                                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.origin_city }}</a>
                                    </td>
                                    <td class="hidden link md:table-cell">
                                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.destination_city }}</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table> 
                {% else %}
                    <div class="h-full w-full flex justify-center items-center pb-4 lg:pb-6">
                        <p class="text-center">No upcoming moves to display</p>
                    </div>
                {% endif %}
            </div>
        </section>
        <section class="card">
            <h3 class="text-center pb-3 border-b border-slate-400 dark:border-slate-600">Parcel Status</h3>
            <div class="h-full">
                {% if parcels %}
                    <div id="chart" class="mx-auto pt-4 sm:pt-5 md:pt-7 lg:pt-9 xl:pt-10 "></div>
                {% else %}
                    <div class="h-full w-full flex justify-center items-center pb-4 lg:pb-6">
                        <p class="text-center">No parcel data to display</p>
                    </div>
                {% endif %}
            </div>
        </section>
        <section class="card">
            <h3 class="text-center pb-3 border-b border-slate-400 dark:border-slate-600">Quick Access</h3>
            <div class="mt-4 sm:mt-5 md:mt-7 lg:mt-9 xl:mt-10 grid grid-cols-2 sm:max-md:grid-cols-3 xl:grid-cols-3 2xl:grid-cols-4 gap-2 sm:gap-3 lg:gap-4">
                <a class="card hover:bg-slate-100 dark:hover:bg-slate-800 flex flex-nowrap items-center p-1 md:p-2 xl:p-3" href="{% url 'tracker:receiving' %}">
                    <div class="size-10 md:size-11 xl:size-12 rounded-full bg-red-500/80 p-1 md:p-2 xl:p-3 text-slate-200 md:text-lg text-center flex justify-center items-center flex-none">
                        <i class="fa-solid fa-qrcode mx-auto"></i>
                    </div>
                    <div class="ml-3">
                        <p class="font-semibold mb-1">Receiving</p>
                        <p class="text-xs">Scan parcels to update status</p>
                    </div>
                </a>
                <a class="card hover:bg-slate-100 dark:hover:bg-slate-800 flex flex-nowrap items-center p-1 md:p-2 xl:p-3" href="{% url 'tracker:moves-list' %}">
                    <div class="size-10 md:size-11 xl:size-12 rounded-full bg-blue-600/80 p-1 md:p-2 xl:p-3 text-slate-200 md:text-lg text-center flex justify-center items-center flex-none">
                        <i class="fa-solid fa-route mx-auto"></i>
                    </div>
                    <div class="ml-3">
                        <p class="font-semibold mb-1">Moves</p>
                        <p class="text-xs">Manage your moves</p>
                    </div>
                </a>
                <a class="card hover:bg-slate-100 dark:hover:bg-slate-800 flex flex-nowrap items-center p-1 md:p-2 xl:p-3" href="{% url 'tracker:move-create' %}">
                    <div class="size-10 md:size-11 xl:size-12 rounded-full bg-violet-500/80 p-1 md:p-2 xl:p-3 text-slate-200 md:text-lg text-center flex justify-center items-center flex-none">
                        <i class="fa-solid fa-truck mx-auto"></i>
                    </div>
                    <div class="ml-3">
                        <p class="font-semibold mb-1">New Move</p>
                        <p class="text-xs">Create a new move</p>
                    </div>
                </a>
                <a class="card hover:bg-slate-100 dark:hover:bg-slate-800 flex flex-nowrap items-center p-1 md:p-2 xl:p-3" href="{% url 'tracker:edit-profile' user.id %}">
                    <div class="size-10 md:size-11 xl:size-12 rounded-full bg-amber-400/80 p-1 md:p-2 xl:p-3 text-slate-200 md:text-lg text-center flex justify-center items-center flex-none">
                        <i class="fa-solid fa-user mx-auto"></i>
                    </div>
                    <div class="ml-3">
                        <p class="font-semibold mb-1">Edit Profile</p>
                        <p class="text-xs">Edit your profile or password</p>
                    </div>
                </a>
            </div>
        </section>
        <section class="card">
            <h3 class="text-center pb-3 border-b border-slate-400 dark:border-slate-600">Recent</h3>
            <div class="h-full">
                {% if recent_pages %}
                    <ul class="pt-4 sm:pt-5 md:pt-7 lg:pt-9 xl:pt-10 list-none w-full divide-y divide-slate-400 dark:divide-slate-500">
                        {% for page in recent_pages %}
                            <li class="w-full flex">
                                <a href="{{ page.url }}" class="w-full hover:bg-slate-100 dark:hover:bg-slate-800 text-center py-3">{{ page.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="w-full flex justify-center items-center h-full pb-4 lg:pb-6">
                        <p class="text-center">No recent history to display</p>
                    </div>
                {% endif %}
            </div>
        </section>
    </section>
</div>
<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script>
    const options = {
        series: Object.values({{ parcels|safe }}),
        labels: Object.keys({{ parcels|safe }}),
        chart: {
            foreColor: document.classList?.includes("dark") ? "#94a3b8" : "#64748b",
            id: "parcel-chart",
            type: "pie"
        },
        colors: ["#0f172a", "#8b5cf6", "#ef4444", "#2563eb", "#facc15", "#10b981"]
    };

    const chart = new ApexCharts(document.querySelector("#chart"), options);

    if ({{ parcels|length }} > 0) {
        chart.render();
    }    
</script>
{% endblock %}

move_minder/tracker/templates/tracker/login.html
<!DOCTYPE html>

{% extends "base.html" %}
{% load static %}

{% block title %}Login | {% endblock %}

{% block main %}
    <div class="my-2 sm:my-3 md:mx-auto md:my-8 md:p-8 lg:p-12 xl:p-16 w-full">
        <form id="login-form" method="post" class="my-2 sm:my-3 mx-0 md:mx-auto md:my-8 rounded-md lg:rounded-lg box p-4 md:p-8 lg:p-12 xl:p-16 w-full md:w-4/5 lg:w-2/3 xl:w-1/2 box-border space-y-4 lg:space-y-6">
        <h2 class="text-center">Log In</h2>
            {% csrf_token %}
            {{ form.as_div }}
            {% if form.errors %}
                <div>
                    <p class="text-red-500 dark:text-red-600 text-sm md:text-base">Please correct the following errors:</p>
                    <ul class="errorlist">
                        {% for field, error_list in form.errors.items %}
                            {% for error in error_list %}
                                <li>{{ field }}: {{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="pt-3">
                <input type="submit" value="Login" class="ml-auto btn primary" />
            </div>
            <p class="text-sm text-center pt-5">New to MoveMinder? 
                <a href="{% url 'tracker:sign-up' %}" class="text-blue-400 underline hover:text-blue-500">Sign up</a>
                 instead!
            </p>
        </form>
    </div>

    <script src="{% static 'tracker/js/form.js' %}"></script>
{% endblock %}

move_minder/tracker/templates/tracker/move_list.html
{% extends "base.html" %}

{% block title %}
My Moves | 
{% endblock %}

{% block main %}
<div class="px-4 lg:px-8 py-4 md:py-6 xl:py-8">
    <section class="flex flex-wrap justify-between content-between sm:content-end gap-3 md:gap-4 lg:gap-6 mb-8 md:mb-12 lg:mb-16 xl:mb-20">
        <h2>My Moves</h2>
        <a class="btn cool max-sm:w-full mt-4 sm:mt-0 sm:ml-4 dark:bg-violet-700" href="{% url 'tracker:move-create' %}">
            <span class="hidden sm:max-md:inline">New Move</span>
            <span class="sm:max-md:hidden">Create New Move</span>
        </a>
    </section>
    {% if moves %}
    <table id="moves-table" class="pt-4 sm:pt-5 md:pt-7 lg:pt-9 xl:pt-10 border-collapse border border-slate-400 dark:border-slate-500 border-spacing-0 w-full table-auto text-center">
        <thead class="bg-slate-200 dark:bg-slate-700">
            <tr class="p-1 sm:p-2 lg:p3">
                <th>Start<span class="max-md:hidden">&nbsp; Date</span></th>
                <th class="max-md:hidden">End<span class="max-md:hidden">&nbsp; Date</span></th>
                <th>Nickname</th>
                <th>Owner</th>
                <th class="max-lg:hidden">Additional Users</th>
                <th class="hidden md:table-cell">From</th>
                <th class="hidden md:table-cell">To</th>
            </tr>
        </thead>
        <tbody>
            {% for move in moves %}
                <tr class="border-t border-t-slate-400 dark:border-t-slate-500 px-1 sm:px-2 lg:px-3 sm:py-1 lg:py-2 hover:bg-slate-100 dark:hover:bg-slate-800">
                    <td class="link">
                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.start_date|date:"SHORT_DATE_FORMAT" }}</a>
                    </td>
                    <td class="max-md:hidden link cursor-pointer" onclick="window.location='{% url "tracker:move-detail" move.id %}'">
                        <a href="{% url 'tracker:move-detail' move.id %}" class="block w-full">{{ move.end_date|date:"SHORT_DATE_FORMAT" }}</a>
                    </td>
                    <td class="link">
                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.nickname }}</a>
                    </td>
                    <td class="link">
                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.primary_user.first_name }} {{ move.primary_user.last_name }}</a>
                    </td>
                    <td class="link cursor-pointer max-lg:hidden" onclick="window.location='{% url "tracker:move-detail" move.id %}'">
                        <a href="{% url 'tracker:move-detail' move.id %}" class="block w-full">
                            <ul class="list-disc">
                            {% for user in move.secondary_users.all %}
                                <li>{{ user.first_name }} {{ user.last_name }}</li>
                            {% endfor %}
                            </ul>
                        </a>
                    </td>
                    <td class="hidden link md:table-cell">
                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.origin_city }}<span class="hidden lg:inline">, {{ move.origin_state_province }}</span></a>
                    </td>
                    <td class="hidden link md:table-cell">
                        <a href="{% url 'tracker:move-detail' move.id %}" class="block">{{ move.destination_city }}<span class="hidden lg:inline">, {{ move.destination_state_province }}</span></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table> 
{% else %}
    <div class="h-full w-full flex justify-center items-center pb-4 lg:pb-6">
        <p class="text-center">You have no moves to display</p>
    </div>
{% endif %}
<div>
{% endblock %}