move_minder/move_minder/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', include('pwa.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

move_minder/tracker/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import HomePageView, SignupView, CustomLoginView, UserUpdateView, DashboardView, UserListView, UserDetailView, MoveListView, MoveDetailView, MoveCreateView, MoveUpdateView, MoveDeleteView,ParcelDetailView, ParcelCreateView, ParcelUpdateView, ParcelDeleteView, ReceivingView, LabelPreview, ShipParcelsView, EndReceivingView, ReceiveParcelView

app_name = "tracker"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("sign-up/", SignupView.as_view(), name="sign-up"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("users/", UserListView.as_view(), name="users-list"),
    path("users/<int:pk>/edit/", UserUpdateView.as_view(), name="edit-profile"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
    path("moves/", MoveListView.as_view(), name="moves-list"),
    path("moves/<int:pk>/", MoveDetailView.as_view(), name="move-detail"),
    path("moves/new/", MoveCreateView.as_view(), name="move-create"),
    path("moves/<int:pk>/edit/", MoveUpdateView.as_view(), name="move-update"),
    path("moves/<int:pk>/delete/", MoveDeleteView.as_view(), name="move-delete"),
    path("moves/<int:move_id>/parcels/<int:pk>/", ParcelDetailView.as_view(), name="parcel-detail"),
    path("moves/<int:pk>/parcels/new/", ParcelCreateView.as_view(), name="parcel-create"),
    path("moves/<int:move_id>/parcels/<int:pk>/edit/", ParcelUpdateView.as_view(), name="parcel-update"),
    path("moves/<int:move_id>/parcels/<int:pk>/delete/", ParcelDeleteView.as_view(), name="parcel-delete"),
    path("parcels/receiving/", ReceivingView.as_view(), name="receiving"),
    path("parcels/<int:pk>/receiving/update-status/", ReceiveParcelView.as_view(), name="receive-parcel"),
    path("labels/", LabelPreview.as_view(), name="label-preview"),
    path("moves/<int:move_id>/parcels/bulk-ship/", ShipParcelsView.as_view(), name="bulk-ship"),
    path("moves/<int:move_id>/end-receiving/", EndReceivingView.as_view(), name="end-receiving")
]

move_minder/tracker/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import ModelForm
import json
from .models import Parcel, UserProfile, Move
from phonenumber_field.formfields import PhoneNumberField

class ParcelStatusForm(ModelForm):
    class Meta:
        model = Parcel
        fields = ["status"]

class SignUpForm(UserCreationForm):
    phone = PhoneNumberField()
    first_name = forms.CharField(max_length=40, required=True)
    last_name = forms.CharField(max_length=40, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "first_name", "last_name", "email", "phone"]

    def clean(self):
        cleaned_data = super(ModelForm, self).clean()
        return cleaned_data

    def is_valid(self):
        valid = super().is_valid()
        print(f"Valid: {valid}")
        if not valid:
            errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
            for field, field_errors in self.errors.items():
                if field != '__all__':
                    continue
                for error in field_errors:
                    errors.append(error)
        return valid

class UpdateUserForm(ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput, required=False)
    phone = PhoneNumberField()

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "first_name", "last_name", "email", "phone"]

        def __init__(self, *args, **kwargs):
            self.user = kwargs.get("instance", None)
            super().__init__(*args, **kwargs)

            self.fields["username"].initial = self.user.username
            self.fields["first_name"].initial = self.user.first_name
            self.fields["last_name"].initial = self.user.last_name
            self.fields["email"].initial = self.user.email

        def clean_password2(self):
            password1 = self.cleaned_data.get("password1")
            password2 = self.cleaned_data.get("password2")
            if password1 and password2 and password1 != password2:
                raise ValidationError("Passwords don't match")
            return password2

class MoveForm(ModelForm):
    start_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = Move
        fields = ["nickname", "primary_user", "secondary_users", "start_date", "end_date", "origin_address1", "origin_address2", "origin_city", "origin_state_province", "origin_postal_code", "origin_country", "destination_address1", "destination_address2", "destination_city", "destination_state_province", "destination_postal_code", "destination_country"]

        def __init__(self, *args, request=None, **kwargs):
            self.user = kwargs.get("instance", None)
            super().__init__(*args, **kwargs)
            self.request = request

            if request is not None and request.resolver_match.url_name == "move-update":
                instance = kwargs.get("instance")
                for field in self.fields.keys():
                    self.field[field].initial = instance[field]

class ParcelForm(ModelForm):
    class Meta:
        model = Parcel
        fields = ["move_id", "type", "room", "contents", "photo", "weight", "status"]
    
        def __init__(self, *args, request=None, **kwargs):
            self.user = kwargs.get("instance", None)
            super().__init__(*args, **kwargs)
            self.request = request

            if request is not None and request.resolver_match.url_name == "parcel-update":
                instance = kwargs.get("instance")
                for field in self.fields.keys():
                    self.field[field].initial = instance[field]

move_minder/tracker/views.py
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django import forms
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.sites.requests import RequestSite
from django.contrib.sites.models import Site
from django.core.exceptions import ImproperlyConfigured
from django.db.models import Q, Count
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.base import TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import ParcelStatusForm, SignUpForm, UpdateUserForm, MoveForm, ParcelForm
import json
from .models import Move, Parcel, UserProfile
from move_minder.sitemaps import StaticViewSitemap
import os
from phonenumber_field.formfields import PhoneNumberField
import re

# Create your views here.
class SitemapMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        request_site = RequestSite(self.request)

        try:
            current_site = Site.objects.get_current(request_site)
        except ImproperlyConfigured:
            current_site = None

        context['current_site'] = current_site
        sitemap = StaticViewSitemap(request_site=request_site, current_site=current_site)
        context['sitemap'] = sitemap.get_urls()

        for url in context['sitemap']:
            url['name'] = " ".join(url['item'].split(":")[-1].split("-")).title()
        return context
    
class AnonymousUserMixin(UserPassesTestMixin):
    def test_func(self):
        return not self.request.user.is_authenticated
    
    def handle_no_permission(self):
        return HttpResponseRedirect(reverse_lazy("tracker:dashboard"))

class HomePageView(SitemapMixin, TemplateView):
    template_name = "tracker/home.html"

    """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # add additional context as necessary
        return context
    """

class SignupView(SitemapMixin, AnonymousUserMixin, CreateView):
    model = UserProfile
    template_name = "tracker/signup.html"
    success_url = reverse_lazy('tracker:login')
    form_class = SignUpForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = context.get("form")
        if form:
            context["form_errors"] = form.errors
        return context
    
    def form_valid(self, form):
        user = form.save()
        phone = form.cleaned_data["phone"]
        UserProfile.objects.create(user=user, phone=phone)
        return super().form_valid(form)
    
    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class CustomLoginView(SitemapMixin, AnonymousUserMixin, LoginView):
    model = UserProfile
    template_name = "tracker/login.html"
    success_url = reverse_lazy("tracker:dashboard")
    form_class = AuthenticationForm

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

class UserUpdateView(SitemapMixin, LoginRequiredMixin, UpdateView):
    model = User
    template_name = "tracker/user_update.html"
    form_class = UpdateUserForm

    def get_initial(self):
        initial = super().get_initial()
        user = self.get_object()
        profile = UserProfile.objects.get(user=user)
        initial["phone"] = profile.phone
        return initial

    def get_success_url(self):
        return reverse("tracker:user-detail", kwargs={"pk": self.request.user.id})
    
    def get(self, request, *args, **kwargs):
        url = request.path
        user = User.objects.select_related("userprofile").get(id=request.user.id)
        history = user.userprofile.recent_pages
        for i in range(len(history)):
            if history[i]["name"] == "Edit Profile":
                history.pop(i)
                break
        history.insert(0, { "name": "Edit Profile", "url": url })
        while len(history) > 10:
            history.pop()
        user.userprofile.recent_pages = history
        user.userprofile.save()
        return super().get(request, *args, **kwargs)
    
    def form_valid(self, form):
        user = form.save()
        phone = form.cleaned_data["phone"]
        UserProfile.objects.filter(user=user).update(phone=phone)
        return super().form_valid(form)

class DashboardView(SitemapMixin, LoginRequiredMixin, TemplateView):
    template_name = "tracker/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = date.today()
        try:
            user_id = self.request.user.id
            moves = Move.objects.filter(
                Q(primary_user=user_id) | Q(secondary_users__in=[user_id]),
            )

            upcoming = moves.filter(
                start_date__gte=today
            ).values(
                "id",
                "nickname",
                "start_date",
                "primary_user__first_name",
                "primary_user__last_name",
                "origin_city",
                "destination_city"
            ).order_by(
                "start_date", 
                "origin_city", 
                "destination_city"
            )
            context["moves"] = upcoming[:10]

            parcels_query = Parcel.objects.filter(move_id__in=moves).aggregate(
                packed=Count("id", filter=Q(status="Packed")),
                in_transit=Count("id", filter=Q(status="In Transit")),
                lost=Count("id", filter=Q(status="Lost")),
                received=Count("id", filter=Q(status="Received")),
                damaged=Count("id", filter=Q(status="Damaged")),
                accepted=Count("id", filter=Q(status="Accepted"))
            )

            parcels = {}
            if len(parcels_query) > 0:
                for key, value in parcels_query.items():
                    new_key = re.sub("_", " ", key.title())
                    parcels[new_key] = value
            else:
                parcels = {
                    "Packed": 0,
                    "In Transit": 0,
                    "Lost": 0,
                    "Received": 0,
                    "Damaged": 0,
                    "Accepted": 0
                }
            
            context["parcels"] = parcels

            recent = UserProfile.objects.filter(user=user_id).values("recent_pages")
            recent_pages = list(recent)[0]["recent_pages"][:10]
            context["recent_pages"] = recent_pages
            
        except Exception as e:
            print(e)
        return context

class UserListView(SitemapMixin, LoginRequiredMixin, ListView):
    model = User
    paginate_by = 50
    context_object_name = "users"

class UserDetailView(SitemapMixin, LoginRequiredMixin, DetailView):
    model = User
    template_name = "tracker/user_detail.html"

    def get_queryset(self):
        path = self.request.path_info.split("/")
        user_id = path[2]
        qs = User.objects.select_related("userprofile").filter(pk=user_id)
        return qs

class MoveListView(SitemapMixin, LoginRequiredMixin, ListView):
    paginate_by = 10
    context_object_name = "moves"

    def get_queryset(self):
        user = User.objects.get(pk=self.request.user.id)
        moves = Move.objects.select_related("primary_user").filter(Q(primary_user=user) | Q(secondary_users__in=[user])).order_by("-start_date")
        return moves
    
    def get(self, request, *args, **kwargs):
        url = request.path
        user = User.objects.select_related("userprofile").get(id=request.user.id)
        history = user.userprofile.recent_pages
        for i in range(len(history)):
            if history[i]["name"] == "My Moves":
                history.pop(i)
                break
        history.insert(0, { "name": "My Moves", "url": url })
        while len(history) > 10:
            history.pop()
        user.userprofile.recent_pages = history
        user.userprofile.save()
        return super().get(request, *args, **kwargs)

class MoveDetailView(SitemapMixin, LoginRequiredMixin, DetailView):
    model = Move

    def get_context_data(self, **kwargs):
        move_id = get_object_or_404(Move, pk=self.kwargs["pk"])

        context = super().get_context_data(**kwargs)
        parcels = Parcel.objects.filter(move_id=move_id)
        context["parcels"] = parcels
        parcel_status_query = parcels.aggregate(
            packed=Count("id", filter=Q(status="Packed")),
            in_transit=Count("id", filter=Q(status="In Transit")),
            lost=Count("id", filter=Q(status="Lost")),
            received=Count("id", filter=Q(status="Received")),
            damaged=Count("id", filter=Q(status="Damaged")),
            accepted=Count("id", filter=Q(status="Accepted"))
        )
        
        parcel_status = {}
        if len(parcel_status_query) > 0:
            for key, value in parcel_status_query.items():
                new_key = re.sub("_", " ", key.title())
                parcel_status[new_key] = value
        else:
            parcel_status = {
                "Packed": 0,
                "In Transit": 0,
                "Lost": 0,
                "Received": 0,
                "Damaged": 0,
                "Accepted": 0
            }
        
        context["parcel_status"] = parcel_status

        return context
    
    def get(self, request, *args, **kwargs):
        url = request.path
        user = User.objects.select_related("userprofile").get(id=request.user.id)

move_minder/tracker/templates/tracker/components/footer.html
<!DOCTYPE html>

{% load static %}

<footer class="mt-4 md:mt-6 lg:mt-8">
    <section id="sitemap" class="box py-4 sm:py-6 md:py-8 lg:py-16 xl:-py-20 px-3 sm:px-5 md:px-6 lg:px-7 xl:px-8 w-full">
        <div class="w-full mx-auto md:w-11/12 lg:w-5/6 xl:w-4/5 space-y-2 sm:space-y-4 lg:space-y-6">
            <h5>Sitemap</h5>
            <div class="flex flex-wrap w-full gap-y-2 md:gap-y-3 justify-between text-sm">
                {% for item in sitemap %}
                    <a href="{{ item.location }}" class="text-nowrap hover:underline hover:text-slate-500 hover:dark:text-slate-200">{{item.name}}</a>
                {% endfor %}
            </div>
        </div>
    </section>
    <section id="copyright" class="py-2 sm:py-3 md:py-4 lg:py-7 lx:py-8 px-3 sm:px-5 md:px-6 lg:px-7 xl:px-8 w-full">
        <p class="text-center">&copy; {% now "Y" %}. Made with &#x2764; by Ryan Moscoe</p>
    </section>
</footer>

move_minder/tracker/templates/tracker/components/header.html
<!DOCTYPE html>

{% load static %}

<header class="page cursor-pointer flex flex-nowrap items-center justify-between fixed top-0 left-0 right-0 z-30 p-2">
    <section class="flex flex-nowrap items-center justify-between space-x-6 px-2">
        {% if user.is_authenticated %}
            <button id="nav-burger" class="lg:hidden">
                <h2>
                    <i class="fa-solid fa-bars"></i>
                </h2>
            </button>
        {% endif %}
        <a class="flex flex-nowrap items-center justify-between space-x-3" href="{% if user.logged_in %}/dashboard/{% else %}/{% endif %}">
            <img src="/static/tracker/box-house.png" alt="Logo: a box with open flaps forming the shape of a house" class="size-8 sm:size-10 md:size-12 lg:size-14" />
            <h1>MoveMinder</h1>
        </a>
    </section>
    {% if user.is_authenticated %}
        <nav class="hidden lg:flex lg:flex-nowrap text-xl text-slate-900 dark:text-slate-200 md:justify-around lg:items-end space-x-4 lg:space-x-5 xl:space-x-6">
            <a class="block mt-4 cursor-pointer hover:text-slate-800 hover:underline dark:hover:text-white" href="{% url 'tracker:dashboard' %}">Dashboard</a>
            <a class="block mt-4 cursor-pointer hover:text-slate-800 hover:underline dark:hover:text-white" href="{% url 'tracker:moves-list' %}">My Moves</a>
            <a class="block mt-4 cursor-pointer hover:text-slate-800 hover:underline dark:hover:text-white" href="{% url 'tracker:move-create' %}">Create New Move</a>
            <a class="block mt-4 cursor-pointer hover:text-slate-800 hover:underline dark:hover:text-white" href="{% url 'tracker:receiving' %}">Receiving</a>
        </nav>
    {% endif %}
    <section class="relative flex flex-no-wrap justify-between space-x-2 md:space-x-4 md:text-2xl px-2 items-center text-lg sm:text-xl">
        <button id="theme-toggler">
            <i class="fa-regular fa-moon text-yellow-400 block dark:hidden hover:text-amber-300"></i>
            <i class="fa-solid fa-sun text-yellow-300 hidden dark:block hover:text-amber-300"></i>
        </button>
        {% if user.is_authenticated %}
            <button id="account-menu">
                <i class="fa-regular fa-user text-slate-800 dark:text-slate-200 hover:text-slate-700 dark:hover:text-white"></i>
            </button>
            <div id="account-menu-content" class="hidden absolute right-0 top-full card space-y-3 md:space-y-4 xl:space-y-5 min-w-max text-center card">
                <a class="block w-full hover:text-slate-400 hover:underline dark:hover:text-slate-200" href="{% url 'tracker:edit-profile' user.id %}">My Profile</a>
                <form id="logout-form" method="post" action="{% url 'tracker:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="block w-full hover:text-slate-400 hover:underline dark:hover:text-slate-200">Logout</button>
                </form>
            </div>
        {% endif %}
    </section>
</header>

{% if user.is_authenticated %}
    <div id="sidebar-overlay" class="hidden w-screen h-screen bg-slate-900/30 dark:bg-slate-100/30 fixed top-0 left-0 right-0 z-40 backdrop-blur-sm"></div>

    <aside id="hamburger-menu" class="py-6 fixed left-[-60%] sm:-left-1/2 md:left-[-40%] top-0 h-screen w-3/5 sm:w-1/2 md:w-2/5 box-contrast z-50 px-2 md:px-4 trasition duration-200">
        <div>
            <button id="close-burger" class="cursor-pointer w-full py-2 flex flex-nowrap justify-between items-center text-base sm:text-lg md:text-xl hover:text-white hover:bg-slate-700 dark:hover:text-slate-800 dark:hover:bg-slate-300">
                <div class="space-x-2 flex flex-nowrap">
                    <img src="/static/tracker/box-house.png" alt="Logo: a box with open flaps forming the shape of a house" class="size-4 sm:size-5 md:size-7" />
                    <span>MoveMinder</span>
                </div>
                <i class="fa-regular fa-circle-left"></i>
            </button>
            <hr class="mb-2"/>
        </div>
        <div class="pl-4">
            <a class="block mt-4 cursor-pointer hover:text-white hover:bg-slate-700 dark:hover:text-slate-800 dark:hover:bg-slate-300" href="{% url 'tracker:dashboard' %}">Dashboard</a>
            <a class="block mt-4 cursor-pointer hover:text-white hover:bg-slate-700 dark:hover:text-slate-800 dark:hover:bg-slate-300" href="{% url 'tracker:moves-list' %}">My Moves</a>
            <a class="block mt-4 cursor-pointer hover:text-white hover:bg-slate-700 dark:hover:text-slate-800 dark:hover:bg-slate-300" href="{% url 'tracker:move-create' %}">Create New Move</a>
            <a class="block mt-4 cursor-pointer hover:text-white hover:bg-slate-700 dark:hover:text-slate-800 dark:hover:bg-slate-300" href="{% url 'tracker:receiving' %}">Receiving</a>
        </div>
    </aside>
{% endif %}

<script src="{% static 'tracker/js/header.js' %}"></script>